# Generated by Django 6.1.1 on 2026-09-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='workspace_type',
            field=models.CharField(choices=[('BUSINESS', 'Empresa / PJ'), ('PERSONAL', 'Finanças Pessoais / PF')], default='PERSONAL', max_length=10, verbose_name='Tipo de Carteira'),
        ),
    ]
