# Generated by Django 6.1.1 on 2026-10-02 19:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Gratuito'), ('MONTHLY_PRO', 'Mensal Pro (R$ 9,90/mês)'), ('ANNUAL_PRO', 'Anual Pro (R$ 79,90/ano)')], default='FREE', max_length=20, verbose_name='Plano')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('TRIALING', 'Período de Testes (Trial)'), ('PAST_DUE', 'Pagamento Pendente / Atrasado'), ('CANCELED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('starts_at', models.DateField(default=datetime.date.today, verbose_name='Início da Assinatura')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Vencimento / Expiração')),
                ('gateway_customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Cliente no Gateway')),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Assinatura no Gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
