# Generated by Django 6.1.1 on 2026-09-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('CASH', 'Dinheiro'), ('TRANSFER', 'Transferência / TED')], default='PIX', max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
