# Generated by Django 6.1.1 on 2026-09-25 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finances', '0002_transaction_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('revenue_goal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('expense_limit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accounts.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'year', 'month')},
            },
        ),
    ]
