# Generated by Django 6.1.1 on 2026-09-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finances', '0003_monthlygoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix'), ('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('CASH', 'Dinheiro'), ('TRANSFER', 'Transferência / TED')], default='CREDIT_CARD', max_length=20, verbose_name='Forma de Pagamento')),
                ('due_day', models.PositiveSmallIntegerField(help_text='Dia de cobrança no mês (1-31)', verbose_name='Dia de Cobrança')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.category', verbose_name='Categoria')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Despesa Recorrente',
                'verbose_name_plural': 'Despesas Recorrentes',
                'ordering': ['due_day', 'description'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='finances.recurringexpense'),
        ),
    ]
