# Generated by Django 6.1.1 on 2026-09-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_recurringexpense_transaction_recurring_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='auto_pay',
            field=models.BooleanField(default=True, help_text='Se marcado, confirma como Pago automaticamente após o dia de cobrança.', verbose_name='Baixa Automática (Débito em Conta / Cartão)'),
        ),
    ]
