# Generated by Django 6.1.1 on 2026-09-29 15:53

import django.core.validators
import finances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_recurringexpense_auto_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.FileField(blank=True, help_text='Anexo em imagem ou PDF do comprovante ou fatura.', null=True, upload_to=finances.models.transaction_receipt_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='Comprovante / Fatura'),
        ),
    ]
